# Poker Hands UCI Classifications
The Poker Hands dataset is taken from here: https://archive.ics.uci.edu/ml/datasets/Poker+Hand

In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [25]:
data_train = np.loadtxt('poker-hand-training-true.data', delimiter=',')
print(data_train.shape)

data_test = np.loadtxt('poker-hand-testing.data', delimiter=',')
print(data_test.shape)


(25010, 11)
(1000000, 11)


In [29]:
print(data_train[0,:])
# verify that the file being open is indeed the top of the file.
print(data_test[0,:])

[ 1. 10.  1. 11.  1. 13.  1. 12.  1.  1.  9.]
[ 1.  1.  1. 13.  2.  4.  2.  3.  1. 12.  0.]


In [38]:
# np.append(data_train,"Suit 1", "Card 1", "Suit 2", "Card 2", "Suit 3", "Card 3","Suit 4", "Card 4","Suit 5", "Card 5","Poker Hand", dtype=object)
# # data_test.columns("Suit 1", "Card 1", "Suit 2", "Card 2", "Suit 3", "Card 3","Suit 4", "Card 4","Suit 5", "Card 5","Poker Hand")

# data_train.head()


AttributeError: 'numpy.ndarray' object has no attribute 'head'

Extracting Poker Hand type and features:

In [57]:
X_train = data_train[:,:-1]

selector = [x for x in range(data_train.shape[1]) if x == 10]
y_train = data_train[:, selector]

X_test = data_test[:,:-1]
y_test = data_test[:, selector]

In [65]:
# print(X_train.shape)
# print(X_train[0,:])

# print(y_train.shape)
# print(y_train[0,:])

print(X_test.shape)
print(X_test[0,:])

print(y_test.shape)
print(y_test[0,:])

(25010, 10)
[ 1. 10.  1. 11.  1. 13.  1. 12.  1.  1.]
(25010, 1)
[9.]
(1000000, 10)
[ 1.  1.  1. 13.  2.  4.  2.  3.  1. 12.]
(1000000,)


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

As we can see, the Poker Hands Dataset has 11 columns to represent th etc...